# totalPlayTime unit is minute
totalPlayTime: 2
restTime: 20
# Whether skip the question which has already be answered correctly.
skipAnswered: 0
# checkInterval unit is seconds
checkInterval: 5
# idleInterval unit is minute
idleInterval: 1
awards:
  # the item name to give
  - name: coalblock
    # for translation
    title: Coal Block
    # optional, the defaults to default mod
    mod: default
    # the item count, optional the defaults to 1
    count: 1
  - name: wood
    title: Apple Wood Planks
    count: 3
  - name: stone
    title: Stone
    count: 3
  - name: torch
    title: Torch
  - name: steel_ingot
    title: Steel Ingot
    count: 3
# question list
quiz:
  - id: tutQuizSettingsFileName
    title: "What's the config file name of the quiz mod in world?"
    desc: "enh."
    answer: quiz_config.yml
  - id: tutUnitOfTotalPlayTime
    title: "What's the unit of totalPlayTime?"
    answer: minute
