# totalPlayTime unit is minute, 0 means disable totalPlayTime
totalPlayTime: 20
# the rest time after playing, unit is minute, 0 means disable resetTime
restTime: 10
# Whether skip the question which has already be answered correctly.
skipAnswered: 0
# checkInterval unit is second
checkInterval: 5
# idleInterval unit is minute
idleInterval: 5
# Whether to force the administrator to rest
forceAdminRest: false
# Whether to force the administrator to quiz
forceAdminQuiz: false
# If set to True, the quiz will be asked immediately after joining the game with a delay of `immediateDelay` seconds.
immediateQuiz: true
# the delay time(seconds) to ask the quiz immediately when immediateQuiz is True.
immediateDelay: 30
# the delay time to kick off, unit is second
kickDelay: 2
awards:
  # the item name to give
  - id: coalblock
    # for translation
    title: Coal Block
    # optional, the defaults to default mod
    mod: default
    # the item count, optional the defaults to 1
    count: 1
  - id: wood
    title: Apple Wood Planks
    count: 3
  - id: stone
    title: Stone
    count: 3
  - id: torch
    title: Torch
  - id: steel_ingot
    title: Steel Ingot
    count: 3
  - id: "diamond"
    title: "Diamond"
# question list
quiz:
  - id: tutQuizSettingsFileName
    title: "What's the config file name of the quiz mod in world?"
    desc: "hint: quiz_config.yml"
    answer: quiz_config.yml
  - id: tutUnitOfTotalPlayTime
    title: "What's the unit of totalPlayTime?"
    answer: minute
    desc: "hint: minute"
